baseURL = "https://yonu33.github.io/"
title = "yonu33.github.io"
theme = "coder"
languageCode = "ja-jp"
defaultContentLanguage = "ja"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
    author = "yonu33"
    description = "UoA33 Student"
    info = ["UoA33 Student"]
    avatarURL = "https://avatars.githubusercontent.com/u/175496140"
    dateFormat = "2006-01-02 15:04:05"

    enableTwemoji = true

    colorScheme = "auto"
    hidecolorschemetoggle = false
    
    favicon_32 = "/favicon-32x32.png"
    
    favicon_16 = "/favicon-16x16.png"
    
    apple_touch_icon = "/apple-touch-icon.png"
    
    android_chrome_192 = "/android-chrome-192x192.png"
    android_chrome_512 = "/android-chrome-512x512.png"
    
    manifest = "/site.webmanifest"

[[params.social]]
    name = "AtCoder"
    icon = "fa-solid fa-a"
    weight = 1
    url = "https://atcoder.jp/users/yonu"
[[params.social]]
    name = "Discord"
    icon = "fa-brands fa-discord"
    weight = 2
    url = "https://discord.com/invite/9ZCgqNzqF7"
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github"
    weight = 3
    url = "https://github.com/yonu33/"
[[params.social]]
    name = "mixi2"
    icon = "fa-solid fa-m"
    weight = 4
    url = "https://mixi.social/@yonu"
[[params.social]]
    name = "X"
    icon = "fa-brands fa-x-twitter"
    weight = 5
    url = "https://x.com/i/user/1898003250068262912"
[[params.social]]
    name = "YouTube"
    icon = "fa-brands fa-youtube"
    weight = 6
    url = "https://www.youtube.com/@yonu33"


[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url = "posts/"